### PR TITLE
less intrusive javascript snippet that won't block dom rendering

### PR DESCRIPTION
**Pull request by visnup**
the current snippet blocks all dom rendering until the `notifier.js` is downloaded. this updates the hoptoad notifier js snippet to be fully asynchronous. see: http://code.google.com/apis/analytics/docs/tracking/asyncTracking.html and http://www.woopra.com/docs/async/

also, switch to using `window.location.toString()` so we don't have to worry about escaping the uri server-side. same goes for the `to_json` calls for the other parameters to make sure things are properly escaped in the strings. lastly, the protocol check just isn't necessary; a url of `//hoptoadapp.com/notifier.js` will use the same protocol that was used to request the page.

### CODE REVIEW

**Comment by visnup** [comment]
anyone get a chance to look at this?

**Comment by jyurek** [comment]
Sorry about the delay. So, one problem with asynchronous loading is what happens when notifier.js hasn't loaded when an error occurs? And what kind of browser support is needed for this functionality?

I agree with the second paragraph, though. Those are good changes.

**Comment by visnup** [comment]
that's a good point about early errors, especially load-based errors. I guess it can come down to a trade-off decision between early render performance vs. complete error reporting. would it be useful to use an option to the helper method that would default to non-async, but allow `:async => true` to be passed to `hoptoad_javascript_notifier` to use the async version? maybe that's overkill though.

the `insertBefore` method will work in all browsers that I know of (ie7+). more modern browsers can use an even simpler async attribute in script tags, but I haven't investigated that much yet.

I can rewrite to include just the easy changes first.

**Comment by jyurek** [comment]
That would be awesome, thanks.

**Comment by mike-burns** [comment]
Closing this in favor of keeping our pending pull requests low. @visnup, please re-open with a new pull request as described in the discussion above.

Also, thank you!

-Mike

**Pull request closed without merging**
