### PR TITLE
Update gemspec's development dependencies

### PR DESCRIPTION
**Pull request by cldwalker**
Before running hoptoad_notifier's test, I had to install the development dependencies one by one. This should make it easier the next around with `gem install hoptoad_notifier --dev`

### CODE REVIEW

**Comment by hgmnz** [comment]
Unfortunately this can't work because of how we test the notifier against a bunch of rails versions (see [SUPPORTED_RAILS_VERSIONS](https://github.com/thoughtbot/hoptoad_notifier/blob/master/SUPPORTED_RAILS_VERSIONS) and how [we use that to define cucumber tasks](https://github.com/thoughtbot/hoptoad_notifier/blob/master/Rakefile#L200-218)

Arguably, it could stand to be better documented so that developers can get up and running faster.

**Comment by cldwalker** [comment]
Then why have hardcoded versions https://github.com/thoughtbot/hoptoad_notifier/blob/master/test/helper.rb#L4-10?

**Comment by hgmnz** [comment]
We need to activate and require those gems for running the unit tests and helpers. But we can't use bundler or rubygem dependencies for our integration tests because the suite itself requires many different versions of the same gems and bundler can't handle that out of the box.

**Comment by hgmnz** [comment]
I've created a [rvm gemset dump](https://gist.github.com/877001) that you can [load](http://rvm.beginrescueend.com/gemsets/importing/) if you are using rvm.

**Pull request closed without merging**
