### PR TITLE
Fix hoptoad:deploy for custom port.

### PR DESCRIPTION
**Pull request by deni64k**

### CODE REVIEW

**Comment by gorenje** [comment]
hi, you could also include the secure configuration flag and use https when secure ...

**Comment by deni64k** [comment]
Ok.

**Comment by deni64k** [comment]
Done.

**Comment by gorenje** [comment]
cool - thanks!

**Comment by deni64k** [comment]
Ouch! I just found a bug. The params must be String, not Hash.

**Comment by deni64k** [comment]
Fixed and it works for me. :)

**Comment by gorenje** [comment]
forked, tested, worked - thank you :)

**Comment by usiegj00** [comment]
Thank you! Integrated into the new repo at: https://github.com/airbrake/airbrake

**Pull request closed without merging**
