### PR TITLE
Handle exceptions raised from Rake tasks

### PR DESCRIPTION
**Pull request by leonid-shevtsov**
I've finally taken a try on fixing one of my least liked things about Hoptoad - the fact that exceptions in Rake tasks are not handled.

(More specifically, what annoyed me is how failing cronjobs did not register at Hoptoad, sending a not-too-informative email instead.)

The exceptions are only sent to Hoptoad when `$stdout` is not a TTY, so if you run a rake task manually you get the old vanilla error handling.

I use the rake command line for `component` and pass the current environment to `cgi_vars`.

In Rails 3 applications the handler is enabled by default via railtie, in Rails 2 it should be enabled by including `require "hoptoad_notifier/rake_handler"` into the `Rakefile`.

The patch isn't Rails-dependant, though; you can include the `rake_handler` in practically any `Rakefile` and, assuming you've got your API key set up, the exceptions will go to Hoptoad.

### CODE REVIEW

**Comment by jyurek** [comment]
This looks really interesting. Would you be able to add some tests for it?

**Comment by leonid-shevtsov** [comment]
Oh, I suppose I got that coming. :) Will do tests tomorrow.

**Comment by jyurek** [comment]
Hi, any progress here?

**Comment by leonid-shevtsov** [comment]
Sorry for procrastinating on this - I've had no idea how to test such a feature, so kept laying it off.

Anyways, I've added tests now. They use a harness Rake application which does some crude stubbing - if you know a better way to do this, I would be happy to hear.

I've also tested the handler on my production apps and it's doing its thing without issues.

I've added a configuration option, `rescue_rake_exceptions`, and removed any kind of output suppressing. So you'll see a standard rake error message _and_ a Hoptoad notification (if i's enabled). Output suppressing is better done by `2>&1 >/dev/null`.

(Whoops, rebase messed up the commit set. Nice job, git. The only new commit is [this one](https://github.com/leonid-shevtsov/hoptoad_notifier/commit/28fcf858df53c1803a38b2020c9d4844f37188d4))

**Comment by ndbroadbent** [comment]
We just wrote this functionality too, also for the cronjob reason.
I think we wrote the override in a slightly cleaner way, so if you want to take a look at our approach, we've submitted a [pull request on leonid-shetsov's fork](https://github.com/leonid-shevtsov/hoptoad_notifier/pull/1).  

Edit:  Github's URL engine seems to be broken, so if you get a 404 you just need to refresh the page.

**Comment by shedd** [comment]
Is anything happening with this pull request?  We have a very kludgy solution for this at the moment, which works, but would certainly like to see this built directly into the notifier.

**Comment by leonid-shevtsov** [comment]
My guess is that I did a rebase at the wrong time, the commits have gone awry and the hoptoad guys reasonably don't want to deal with it.

So I've cleaned up the request myself: https://github.com/thoughtbot/hoptoad_notifier/pull/31

Please give this some attention.

**Pull request closed without merging**
